### ISSUE TITLE
Problem with install Clarity

### ISSUE THREAD

**Issue by brunowego** [tobi/clarity#18]
Sorry for the inconvenience, I can not install clarity. Any idea how solve it?

vagrant@quantal64:~$ sudo clarity /var/log --include '_/_*'
/var/lib/gems/1.9.1/gems/clarity-0.9.8/lib/clarity/cli.rb:47:in `block (2 levels) in execute': can't convert String into Array (TypeError)
        from /usr/lib/ruby/1.9.1/optparse.rb:1360:in`call'
        from /usr/lib/ruby/1.9.1/optparse.rb:1360:in `block in parse_in_order'
        from /usr/lib/ruby/1.9.1/optparse.rb:1347:in`catch'
        from /usr/lib/ruby/1.9.1/optparse.rb:1347:in `parse_in_order'
        from /usr/lib/ruby/1.9.1/optparse.rb:1341:in`order!'
        from /usr/lib/ruby/1.9.1/optparse.rb:1432:in `permute!'
        from /usr/lib/ruby/1.9.1/optparse.rb:1453:in`parse!'
        from /var/lib/gems/1.9.1/gems/clarity-0.9.8/lib/clarity/cli.rb:76:in `block in execute'
        from /usr/lib/ruby/1.9.1/optparse.rb:1865:in`options'
        from /var/lib/gems/1.9.1/gems/clarity-0.9.8/lib/clarity/cli.rb:20:in `execute'
        from /var/lib/gems/1.9.1/gems/clarity-0.9.8/bin/clarity:10:in`<top (required)>'
        from /usr/local/bin/clarity:23:in `load'
        from /usr/local/bin/clarity:23:in`<main>'
vagrant@quantal64:~$

Thanks!

**Comment by brunowego** [comment]
Solved, sorry!
