### ISSUE TITLE
Got an error on clarity /var/log --include '/*' 

### ISSUE THREAD

**Issue by rituka** [tobi/clarity#7]
I am pretty naive to clarity. For trial I installed clarity at my mac. And when I try to run clarity /var/log --include '/*'  
It gives me error like 
/Users/ritu/.gem/ruby/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:47:in `+': can't convert String into Array (TypeError)
    from /Users/ritu/.gem/ruby/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:47:in`execute'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1260:in `call'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1260:in`parse_in_order'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1247:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1247:in`parse_in_order'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1241:in `order!'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1332:in`permute!'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1353:in `parse!'
    from /Users/ritu/.gem/ruby/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:76:in`execute'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/optparse.rb:1717:in `options'
    from /Users/ritu/.gem/ruby/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:20:in`execute'
    from /Users/ritu/.gem/ruby/1.8/gems/clarity-0.9.8/bin/clarity:10
    from /usr/bin/clarity:19:in `load'
    from /usr/bin/clarity:19

Can somebody help me in this?

**Comment by morten** [comment]
I see this as well, it's because v0.9.8 of the gem doesn't include this commit http://github.com/tobi/clarity/commit/8f39d2ea141afb9dfd6f58f46c0657cc3c72fbce - any chance of a version bump on the gem?

**Comment by anselmdk** [comment]
Just had to fix this locally.
I'd appreciate a version bump on the gem as well.

**Comment by sohaibiftikhar** [comment]
@anselmdk I am not familiar with either ruby on rails or gem. Could you give me a pointer as to how you fixed it.

**Comment by anselmdk** [comment]
@sohaibiftikhar I'd love to, but unfortunately I moved my entire workflow away from ruby to npm years ago, so I'd be as lost as you. I've actually completely forgotten what I used this tool for in the first place :)
